# Generated by Django 4.0.6 on 2023-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_qty', models.CharField(max_length=12)),
                ('product_prize', models.IntegerField()),
            ],
        ),
    ]
