# Generated by Django 4.2.3 on 2023-07-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_address', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member_address',
            new_name='MemberAddress',
        ),
    ]
