# Generated by Django 4.0.6 on 2023-07-25 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('joined_date', models.DateField(default=datetime.datetime.now)),
                ('city', models.CharField(default='null', max_length=255)),
                ('department', models.CharField(default='null', max_length=255)),
            ],
        ),
    ]
