# Generated by Django 4.0.6 on 2023-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(default='null', primary_key=True, serialize=False),
        ),
    ]
