# Generated by Django 4.0.6 on 2023-07-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_employee_employee_id'),
    ]

    operations = [
    ]
