# Generated by Django 4.0.6 on 2023-07-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20230725_1934'),
    ]

    operations = [
    ]
