# Generated by Django 4.0.6 on 2023-07-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20230725_1943'),
    ]

    operations = [
    ]
