# Generated by Django 4.0.6 on 2023-08-16 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20230726_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
